export const PART1 = "Phần 1 MÔ TẢ HÌNH ẢNH";
export const PART2 = "Phần 2 HỎI - ĐÁP";
export const PART3 = "Phần 3 ĐOẠN HỘI THOẠI";
export const PART4 = "Phần 4 BÀI NÓI CHUYỆN NGẮN";
export const PART5 = "Phần 5 CÂU KHÔNG HOÀN CHỈNH";
export const PART6 = "Phần 6 HOÀN THÀNH ĐOẠN VĂN";
export const PART71 = "Phần 7 ĐOẠN ĐƠN";
export const PART72 = "Phần 7 ĐOẠN KÉP";
export const URLAPI = "http://toeicmentor.club/toeic/";